In [53]:
import numpy as np      
import pandas as pd

In [46]:
import pandas as pd

draft1 = pd.read_csv('ex1.csv',header = None)
draft1

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [57]:
draft2 = pd.read_table('test.tsv')
draft2

test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [45]:
df = pd.read_csv('ex2.csv', names = ['sfafwa', 'effwa', 'WFEWA','aed', 'message'])
df

sfafwa  effwa  WFEWA  aed message
0       1      2      3    4   hello
1       5      6      7    8   world
2       9     10     11   12     foo

In [59]:
nested = pd.read_csv('csv_mindex.csv', index_col=['key1', 'key2'])
nested 

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [55]:
a = pd.read_csv('ex4.csv',names = ['sfafwa', 'effwa', 'WFEWA','aed', 'message'], skiprows =[0,2,3])
a

sfafwa effwa WFEWA aed  message
0      a     b     c   d  message
1      1     2     3   4    hello
2      5     6     7   8    world
3      9    10    11  12      foo

In [64]:
b = pd.read_csv('ex5.csv')
b
pd.isnull(b)

something      a      b      c      d message
0     False  False  False  False  False    True
1     False  False  False   True  False   False
2     False  False  False  False  False   False

In [87]:
b = pd.read_excel('C:/Users/user/Documents/Book1.xlsx', sheet_name = 'xyz')
b

abc  def  ghi
0  pqr  mno  jkl

In [2]:
#import pandas as pd
#url = "https://www.basketball-reference.com/leagues/NBA_2020_games.html"

#BB_data = pd.read_html(url)

#BB_data


AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

In [16]:
import pandas as pd

url = "https://www.basketball-reference.com/leagues/NBA_2020_games.html"

BB_data = pd.read_html(url)

BB_data

[                 Date Start (ET)         Visitor/Neutral  PTS  \
 0   Tue, Oct 22, 2019      8:00p    New Orleans Pelicans  122   
 1   Tue, Oct 22, 2019     10:30p      Los Angeles Lakers  102   
 2   Wed, Oct 23, 2019      7:00p           Chicago Bulls  125   
 3   Wed, Oct 23, 2019      7:00p         Detroit Pistons  119   
 4   Wed, Oct 23, 2019      7:00p     Cleveland Cavaliers   85   
 5   Wed, Oct 23, 2019      7:30p  Minnesota Timberwolves  127   
 6   Wed, Oct 23, 2019      7:30p       Memphis Grizzlies  101   
 7   Wed, Oct 23, 2019      7:30p          Boston Celtics   93   
 8   Wed, Oct 23, 2019      8:30p      Washington Wizards  100   
 9   Wed, Oct 23, 2019      8:30p         New York Knicks  111   
 10  Wed, Oct 23, 2019      9:00p   Oklahoma City Thunder   95   
 11  Wed, Oct 23, 2019     10:00p        Sacramento Kings   95   
 12  Wed, Oct 23, 2019     10:00p          Denver Nuggets  108   
 13  Thu, Oct 24, 2019      7:00p           Atlanta Hawks  117   
 14  Thu, 

In [17]:
url1 = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv", sep = '\t')
url1.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [24]:
url1[['Age','PassengerId']]

Age  PassengerId
0    22.0            1
1    38.0            2
2    26.0            3
3    35.0            4
4    35.0            5
5     NaN            6
6    54.0            7
7     2.0            8
8    27.0            9
9    14.0           10
10    4.0           11
11   58.0           12
12   20.0           13
13   39.0           14
14   14.0           15
15   55.0           16
16    2.0           17
17    NaN           18
18   31.0           19
19    NaN           20
20   35.0           21
21   34.0           22
22   15.0           23
23   28.0           24
24    8.0           25
25   38.0           26
26    NaN           27
27   19.0           28
28    NaN           29
29    NaN           30
..    ...          ...
126   NaN          127
127  24.0          128
128   NaN          129
129  45.0          130
130  33.0          131
131  20.0          132
132  47.0          133
133  29.0          134
134  25.0          135
135  23.0          136
136  19.0          137
137  37.0          138
138  16.0          139
139  24.0          140
140   NaN          141
141  22.0          142
142  24.0          143
143  19.0          144
144  18.0          145
145  19.0          146
146  27.0          147
147   9.0          148
148  36.5          149
149  42.0          150
150  51.0          151
151  22.0          152
152  55.5          153
153  40.5          154
154   NaN          155
155  51.0          156

[156 rows x 2 columns]

In [25]:
url1.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [33]:
c = pd.read_csv('ex6.csv')
c.head(4)

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R

In [30]:
c = pd.read_csv('ex6.csv', nrows= 5)
c

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [38]:
import sys
x = pd.read_csv('ex5.csv') #Load Data
x
x.to_csv('out.csv')      #Store Data

In [40]:
x.to_csv('out1.csv', sep='@')

In [41]:
x.to_csv(sys.stdout, na_rep = 'afwaefsdcnbhbjbk')

,something,a,b,c,d,message
0,one,1,2,3.0,4,afwaefsdcnbhbjbk
1,two,5,6,afwaefsdcnbhbjbk,8,world
2,three,9,10,11.0,12,foo


In [43]:
x.to_csv('out2.csv', index = False, header = False)

In [46]:
x.to_csv('out2.csv', index = False, columns= ['a','b','c'])

In [57]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [65]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('tseries.csv')
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [72]:
dates = pd.date_range('1/1/2000', periods =7)
ts = pd.Series(np.arange(7), index= dates)
ts.to_csv('tseries.csv')
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [71]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7))
ts.to_csv('tseries.csv')
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [73]:
import csv

f = open('ex7.csv')

reader = csv.reader(f)
reader

In [74]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


In [75]:
pd.read_csv('ex7.csv')

a  b  c
0  1  2  3
1  1  2  3

In [76]:
with open('ex7.csv') as f:
    lines = list(csv.reader(f))
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [79]:
c =1,2,3
c 

(1, 2, 3)

In [80]:
header, value = lines[0], lines[1:]

In [ ]:
data_dict = {h: v for h, v in zip(*values)  }

In [84]:
w.to_pickle('frame_pickle')

In [85]:
pd.read_pickle('frame_pickle')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
import pandas as pd

tship = pd_read.csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv', sep='\t')
tship

NameError: name 'pd_read' is not defined

In [13]:
import pandas as pd


In [14]:
tship = pd.csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv', sep='\t')

NameError: name 'pd_read' is not defined

In [15]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')  

In [63]:
a = titanic_train.dtypes[titanic_train.dtypes == 'object'].index

In [64]:
a

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'test'], dtype='object')

In [24]:
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked
count                        156   156     156    31      155
unique                       156     2     145    28        3
top     Bonnell, Miss. Elizabeth  male  237736   D26        S
freq                           1   100       2     2      110

In [26]:
del titanic_train["PassengerId"]

In [34]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [31]:
sorted(titanic_train["Name"])[10:20]

['Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond',
 'Beesley, Mr. Lawrence',
 'Bing, Mr. Lee',
 'Bonnell, Miss. Elizabeth',
 'Boulos, Mrs. Joseph (Sultana)',
 'Braund, Mr. Owen Harris']

In [35]:
titanic_train["Survived"]


0      0
1      1
2      1
3      1
4      0
      ..
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [43]:
pd.Categorical(titanic_train["Survived"])

[0, 1, 1, 1, 0, ..., 1, 0, 0, 0, 0]
Length: 156
Categories (2, int64): [0, 1]

In [44]:
new_survived.rename_categories(["Died", "Survived"])

[Died, Survived, Survived, Survived, Died, ..., Survived, Died, Died, Died, Died]
Length: 156
Categories (2, object): [Died, Survived]

In [45]:
new_survived = pd.Categorical(titanic_train["Survived"])
new_survived = new_survived.rename_categories(["Died","Survived"])

new_survived

[Died, Survived, Survived, Survived, Died, ..., Survived, Died, Died, Died, Died]
Length: 156
Categories (2, object): [Died, Survived]

In [46]:
pd.Categorical(titanic_train["Pclass"])

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [59]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass = new_class.rename_categories(["rahul", "class2", "class3"])
new_Pclass

[class3, rahul, class3, rahul, class3, ..., rahul, class3, class3, class3, rahul]
Length: 156
Categories (3, object): [rahul, class2, class3]

In [50]:
titanic_train["new_survived"] = new_survived
titanic_train.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

  new_survived  
0         Died  
1     Survived  
2     Survived  
3     Survived  
4         Died

In [51]:
titanic_train['test'] = "rahul"
titanic_train

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
151         1       1                  Pears, Mrs. Thomas (Edith Wearne)   
152         0       3                                   Meo, Mr. Alfonzo   
153         0       3                    van Billiard, Mr. Austin Blyler   
154         0       3                              Olsen, Mr. Ole Martin   
155         0       1                        Williams, Mr. Charles Duane   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
151  female  22.0      1      0            113776  66.6000    C2        S   
152    male  55.5      0      0        A.5. 11206   8.0500   NaN        S   
153    male  40.5      0      2          A/5. 851  14.5000   NaN        S   
154    male   NaN      0      0         Fa 265302   7.3125   NaN        S   
155    male  51.0      0      1          PC 17597  61.3792   NaN        C   

    new_survived   test  
0           Died  rahul  
1       Survived  rahul  
2       Survived  rahul  
3       Survived  rahul  
4           Died  rahul  
..           ...    ...  
151     Survived  rahul  
152         Died  rahul  
153         Died  rahul  
154         Died  rahul  
155         Died  rahul  

[156 rows x 13 columns]

In [61]:
titanic_train["Survived"] = new_survived
titanic_train
titanic_train["Pclass"] = new_Pclass
titanic_train

Survived  Pclass                                               Name  \
0        Died  class3                            Braund, Mr. Owen Harris   
1    Survived   rahul  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2    Survived  class3                             Heikkinen, Miss. Laina   
3    Survived   rahul       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4        Died  class3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
151  Survived   rahul                  Pears, Mrs. Thomas (Edith Wearne)   
152      Died  class3                                   Meo, Mr. Alfonzo   
153      Died  class3                    van Billiard, Mr. Austin Blyler   
154      Died  class3                              Olsen, Mr. Ole Martin   
155      Died   rahul                        Williams, Mr. Charles Duane   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
151  female  22.0      1      0            113776  66.6000    C2        S   
152    male  55.5      0      0        A.5. 11206   8.0500   NaN        S   
153    male  40.5      0      2          A/5. 851  14.5000   NaN        S   
154    male   NaN      0      0         Fa 265302   7.3125   NaN        S   
155    male  51.0      0      1          PC 17597  61.3792   NaN        C   

    new_survived   test  
0           Died  rahul  
1       Survived  rahul  
2       Survived  rahul  
3       Survived  rahul  
4           Died  rahul  
..           ...    ...  
151     Survived  rahul  
152         Died  rahul  
153         Died  rahul  
154         Died  rahul  
155         Died  rahul  

[156 rows x 13 columns]

In [62]:
titanic_train.describe()

Age       SibSp       Parch        Fare
count  126.000000  156.000000  156.000000  156.000000
mean    28.141508    0.615385    0.397436   28.109587
std     14.613880    1.056235    0.870146   39.401047
min      0.830000    0.000000    0.000000    6.750000
25%     19.000000    0.000000    0.000000    8.003150
50%     26.000000    0.000000    0.000000   14.454200
75%     35.000000    1.000000    0.000000   30.371850
max     71.000000    5.000000    5.000000  263.000000

In [65]:
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked   test
count                        156   156     156    31      155    156
unique                       156     2     145    28        3      1
top     Bonnell, Miss. Elizabeth  male  237736   D26        S  rahul
freq                           1   100       2     2      110    156

In [72]:
sorted(titanic_train["Name"])[1:5]

['Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan']

In [73]:
titanic_train["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [32]:
titanic_train.dtypes == "object"

Survived    False
Pclass      False
Name         True
Sex          True
Age         False
SibSp       False
Parch       False
Ticket       True
Fare        False
Cabin        True
Embarked     True
dtype: bool

In [82]:
import numpy as np

char_cabin = titanic_train["Cabin"].astype(str)

new_Cabin = np.array([cabin[0] for cabin in char_cabin])

new_Cabin = pd.Categorical(new_Cabin)

new_Cabin

[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [85]:
d = pd.Series([1,2,3,4])
d.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [91]:
missing= np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [92]:
np.where(titanic_train["Age"].isnull() == False)


(array([  0,   1,   2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  18,  20,  21,  22,  23,  24,  25,  27,  30,  33,
         34,  35,  37,  38,  39,  40,  41,  43,  44,  49,  50,  51,  52,
         53,  54,  56,  57,  58,  59,  60,  61,  62,  63,  66,  67,  68,
         69,  70,  71,  72,  73,  74,  75,  78,  79,  80,  81,  83,  84,
         85,  86,  88,  89,  90,  91,  92,  93,  94,  96,  97,  98,  99,
        100, 102, 103, 104, 105, 106, 108, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 122, 123, 124, 125, 127, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 141, 142, 143, 144, 145,
        146, 147, 148, 149, 150, 151, 152, 153, 155], dtype=int64),)

In [96]:
titanic_train.loc[missing][['Name', 'Survived']]

Name  Survived
5                                  Moran, Mr. James      Died
17                     Williams, Mr. Charles Eugene  Survived
19                          Masselmani, Mrs. Fatima  Survived
26                          Emir, Mr. Farred Chehab      Died
28                    O'Dwyer, Miss. Ellen "Nellie"  Survived
29                              Todoroff, Mr. Lalio      Died
31   Spencer, Mrs. William Augustus (Marie Eugenie)  Survived
32                         Glynn, Miss. Mary Agatha  Survived
36                                 Mamee, Mr. Hanna  Survived
42                              Kraeff, Mr. Theodor      Died
45                         Rogers, Mr. William John      Died
46                                Lennon, Mr. Denis      Died
47                        O'Driscoll, Miss. Bridget  Survived
48                              Samaan, Mr. Youssef      Died
55                                Woolner, Mr. Hugh  Survived
64                            Stewart, Mr. Albert A      Died
65                         Moubarek, Master. Gerios  Survived
76                                Staneff, Mr. Ivan      Died
77                         Moutal, Mr. Rahamin Haim      Died
82                   McDermott, Miss. Brigdet Delia  Survived
87                    Slocovski, Mr. Selman Francis      Died
95                      Shorney, Mr. Charles Joseph      Died
101                Petroff, Mr. Pastcho ("Pentcho")      Died
107                          Moss, Mr. Albert Johan  Survived
109                             Moran, Miss. Bertha  Survived
121                      Moore, Mr. Leonard Charles      Died
126                             McMahon, Mr. Martin      Died
128                               Peter, Miss. Anna  Survived
140                   Boulos, Mrs. Joseph (Sultana)      Died
154                           Olsen, Mr. Ole Martin      Died

In [98]:
max(titanic_train['Fare'])

263.0

In [99]:
titanic_train["Fare"] == max(titanic_train['Fare'])

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154    False
155    False
Name: Fare, Length: 156, dtype: bool

In [112]:
np.where(titanic_train["Fare"] == max(titanic_train['Fare']))

(array([27, 88], dtype=int64),)

In [113]:
index = np.where(titanic_train["Fare"] == max(titanic_train['Fare']))

titanic_train.loc[index]

Survived Pclass                            Name     Sex   Age  SibSp  \
27      Died  rahul  Fortune, Mr. Charles Alexander    male  19.0      3   
88  Survived  rahul      Fortune, Miss. Mabel Helen  female  23.0      3   

    Parch Ticket   Fare        Cabin Embarked new_survived   test  
27      2  19950  263.0  C23 C25 C27        S         Died  rahul  
88      2  19950  263.0  C23 C25 C27        S     Survived  rahul

In [131]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [123]:
a = pd.Series(my_data, index=labels)


In [124]:
a[0]

10

In [132]:
a['a']

10

In [133]:
a[0:2]

a    10
b    20
dtype: int64

In [135]:
a[0::]

a    10
b    20
c    30
dtype: int64

In [139]:
d = {'a':10,'b':20,'c':30}
pd.DataFrame(d, index=[40,23,27])

a   b   c
40  10  20  30
23  10  20  30
27  10  20  30

In [140]:
a = {'a':10,'b':20,'c':30}
pd.DataFrame(a, index=[12,13,14])

a   b   c
12  10  20  30
13  10  20  30
14  10  20  30

In [143]:
new = pd.Series([1,2,33,4,'rahul'],index=[12,13,14,3,22])
new

12        1
13        2
14       33
3         4
22    rahul
dtype: object

In [154]:
from numpy.random import randn as rn
matri_data = rn(5,4)
row_label = ['a','B','c','d','e']
coloum_label = ['f', 'g','h','i']

df = pd.DataFrame(matri_data,row_label,coloum_label)
df

f         g         h         i
a  1.440417 -0.439606 -0.265349 -0.877632
B -0.405140 -0.961594  1.884578 -0.649253
c  0.506787  0.825168 -0.381870 -0.287289
d  0.072524 -0.213947 -0.435181 -1.618828
e  0.938800 -1.518015 -0.657830  0.634488

In [155]:
df

f         g         h         i
a  1.440417 -0.439606 -0.265349 -0.877632
B -0.405140 -0.961594  1.884578 -0.649253
c  0.506787  0.825168 -0.381870 -0.287289
d  0.072524 -0.213947 -0.435181 -1.618828
e  0.938800 -1.518015 -0.657830  0.634488

In [153]:
rn(5,4)

array([[-1.23697915,  2.05355074, -0.5417098 ,  0.43323172],
       [ 1.34332365, -0.07629472, -1.96609968,  1.02276804],
       [-0.24470019, -0.61027215, -1.69110475, -0.97268974],
       [ 0.60143916,  1.03332384,  0.73874353,  0.38793409],
       [-0.15948337,  1.32531558, -0.23669104,  0.33402819]])

In [162]:
df[['f','g','h']]

f         g         h
a  1.440417 -0.439606 -0.265349
B -0.405140 -0.961594  1.884578
c  0.506787  0.825168 -0.381870
d  0.072524 -0.213947 -0.435181
e  0.938800 -1.518015 -0.657830

In [163]:
df.iloc[2]

f    0.506787
g    0.825168
h   -0.381870
i   -0.287289
Name: c, dtype: float64

In [88]:
titanic_train.head(4)

Survived  Pclass                                               Name  \
0      Died  class3                            Braund, Mr. Owen Harris   
1  Survived   rahul  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2  Survived  class3                             Heikkinen, Miss. Laina   
3  Survived   rahul       Futrelle, Mrs. Jacques Heath (Lily May Peel)   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   

  new_survived   test  
0         Died  rahul  
1     Survived  rahul  
2     Survived  rahul  
3     Survived  rahul